# Generated by Django 6.1 on 2026-09-07 10:17

import works.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workimage',
            name='image',
            field=models.ImageField(upload_to=works.models.work_image_upload_path),
        ),
    ]
